### ISSUE TITLE
Not working on Ios mobile

### ISSUE THREAD

**Issue by Oxicode** [mburakerman/numscrubberjs#1]

**Comment by Oxicode** [comment]
![screenshot_20170313-100532](https://cloud.githubusercontent.com/assets/1320709/23860380/c8f63e9c-07d4-11e7-8e04-80c6926f9bb6.png)

**Comment by mburakerman** [comment]
I have tried on my android phone, it works. 
You tried to drag your finger on input field left & right, right?

**Comment by jkingsman** [comment]
iOS Chrome 56.0.2924.79 and the built in Reddit browser (which I assume is just a Safari frame?) don't work at all, even when zoomed out to prevent page zoom rubber banding (zoomed in from when the box was focused).

**Comment by mburakerman** [comment]
I see.

 I use input range in my code so it causes the problem on iphone.
 I found a cross browser solution with [this](https://github.com/dwyl/range-touch). 
Will try on this.

**Comment by mburakerman** [comment]
How can i test it after adding [this  iphone solution](https://github.com/dwyl/range-touch) to my code?

Plus it is 2kb and gonna make plugin 2 times heavy.

**Comment by jkingsman** [comment]
I mean it's up to you whether you wanna add it or not ¯\_(ツ)_/¯ If you stick it in a branch with an example page, I'll clone/host locally and let you know what it's like.

**Comment by mburakerman** [comment]
You can fork and try with [this](https://github.com/dwyl/range-touch/blob/master/range-touch.min.js)
If you try, put that code to the bottom!

If you try and see it works, let me know please^^.

**Comment by jkingsman** [comment]
Looks like that requires jQuery, but even when I add it, it doesn't work...

**Comment by mburakerman** [comment]
Oh okay i didn't realize jQuery dependency.
Actually i don't know how to fix this issue. Will work on it...

**Comment by eko24ive** [comment]
Hey @mburakerman just tested your code from `master` branch which is on https://mburakerman.github.io/numscrubberjs/ on IOS version 10.2 and everything works ok.
But there is issues with android devices indeed. It's reproducable via emulation mode in Chrome.

**Comment by mburakerman** [comment]
On which android device there is issue? I have tested on my android device and works fine.

**Comment by eko24ive** [comment]
Well I tested on my Xiaomi Mi Max, but I was able to reporduce it via Chrome emulation mode on Nexus 6P
