### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by arjunmenon** [mburakerman/numscrubberjs#3]
For purpose of UX, I would suggest some indication which describes the left-right behaviour.

The behaviour itself is intuitive but it is not obvious. The default behaviour sure does not feel easy to use but is more indicative.

**Comment by mburakerman** [comment]
Unfortunately i don't agree with you. It's pretty intuitive. How come it's not obvious and not easy to use?

**Comment by arjunmenon** [comment]
I refer the default behaviour to the browsers and not numscrubberjs.
So for what the browser gives, at first sight, you are immediately made aware that it is about a range field. That is what makes it obvious to understand what it is. But surely, the controls for it seems cramped. So not that intuitive.

As for numbscrubberjs, it feels more intuitive, easy to use, kind of obvious on how it should behave, but, and heavily but, at first glance tells nothing about what it is. Just a textfield with number and which has no way to edit. I need to play The Slow Dance with my mouse if I have to get precise.

I am sure you have heard about this, 

> UX is like a joke, if you need to explain, it ain't good.

**Comment by mburakerman** [comment]
> at first glance tells nothing about what it is

I say again, i don't agree with you. It's as obvious as default behavior. Plus, more funny to play.
